### ISSUE TITLE
Words with symbols in them and also spaced-out words get past the filter

### ISSUE THREAD

**Issue by Bytedefined** [jojoee/leo-profanity#26]
As seen in the two images below, if you replace a letter with a symbol, it gets past the filter, and if you space the word out, it gets past the filter.
![image](https://user-images.githubusercontent.com/56295147/175760667-707d91d5-0b31-4c20-b4d3-3a546a72ea43.png)
![image](https://user-images.githubusercontent.com/56295147/175760675-82507d2a-04b9-478f-93c6-5b4e579afb51.png)

**Comment by Bytedefined** [comment]
Update: Seems that words without spaces also get passed the filter
![image](https://user-images.githubusercontent.com/56295147/175760719-8fd3db92-32c2-4f50-8fa5-1a9f1e1a162a.png)

**Comment by jojoee** [comment]
Hi @Bytedefined
I understand your point but this is what to be expected from this filter library.

There have many approaches to make the profanity/bad-word filter like
- word-based (this library)
- NLP based (a complex one)
- word and other sanitize/filter methods
For word-based approaches, we can't capture the tricks that you mentioned (space/symbol replacement), the reason is provided here https://github.com/jojoee/leo-profanity#filter

Best,

**Comment by jojoee** [comment]
Due to no response, I'm closing the issue.
Please ping me if any updates to it 🙏
